// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package motauto;

/************************************************************/
/**
 * 
 */
public class Articulos {
	/**
	 * 
	 */
	private String codigo;
	/**
	 * 
	 */
	private String nombre;
	/**
	 * 
	 */
	private EcorePrimitiveTypes.EFloat precio;
	/**
	 * 
	 */
	private EcorePrimitiveTypes.EFloat iva;

	/**
	 * 
	 * @param Insert Correcte 
	 */
	public static void insertArticulo(boolean Insert Correcte) {
	}

	/**
	 * 
	 */
	public void modificarArticulo() {
	}

	/**
	 * 
	 */
	public static void ImprimirArticulo() {
	}
};
