// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package motauto;

/************************************************************/
/**
 * 
 */
public class Cliente {
	/**
	 * 
	 */
	private String dni;
	/**
	 * 
	 */
	private String nombre;
	/**
	 * 
	 */
	private String apellidos;
	/**
	 * 
	 */
	private String correo;
	/**
	 * 
	 */
	private int telefono;
	/**
	 * 
	 */
	private String direccion;

	/**
	 * 
	 * @param creacioncorrecta 
	 */
	public static void insertCliente(boolean creacioncorrecta) {
	}

	/**
	 * 
	 */
	public static void ImprmirClient() {
	}

	/**
	 * 
	 */
	public static void modificarCliente() {
	}
};
