// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package motauto;

/************************************************************/
/**
 * 
 */
public class Comprovaciones {
	/**
	 * 
	 * @param dni 
	 * @param existe 
	 */
	public static void comprovarDni(String dni, boolean existe) {
	}

	/**
	 * 
	 * @param codigoArticulo 
	 * @return 
	 */
	public static boolean comprovarCodigoArticulo(String codigoArticulo) {
		return false;
	}

	/**
	 * 
	 * @param matricula 
	 * @param Existeix 
	 */
	public static void comprovarMatricula(String matricula, boolean Existeix) {
	}

	/**
	 * 
	 * @param DNI 
	 * @param Client 
	 */
	public static void consultaClient(String DNI, Cliente Client) {
	}

	/**
	 * 
	 * @param Matricula 
	 * @param Vehiculo 
	 */
	public static void consultaVehiculo(String Matricula, Vehiculo Vehiculo) {
	}

	/**
	 * 
	 * @param codigoArticulo 
	 * @param Articulo 
	 */
	public static void consultaArticulo(String codigoArticulo, Articulos Articulo) {
	}

	/**
	 * 
	 * @param numFactura 
	 * @param Factura 
	 */
	public static void consultaFactura(int numFactura, FacturaHeader Factura) {
	}

	/**
	 * 
	 * @param numFactura 
	 * @param Existeix 
	 */
	public static void comprovarNumeroFactura(String numFactura, boolean Existeix) {
	}
};
