// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package motauto;

import java.sql.ResultSet;
import java.sql.SQLException;

/************************************************************/
/**
 * 
 */
public class Comprovaciones {
	/**
	 * 
	 * @param dni 
	 * @param existe 
	 */
	public static void comprovarDni(String dni, boolean existe) {
	}

	/**
	 * 
	 * @param codigoArticulo 
	 * @return 
	 */
	public static boolean comprovarCodigoArticulo(String codigoArticulo) 
	{
		Database db = new Database();
		boolean trobat = false;
		
		try 
		{
            ResultSet rs = db.ExecuteQuery("SELECT * FROM articulos WHERE codigo = '"+codigoArticulo+"';");
            
            while (rs.next()) 
            {
            	trobat = true;
            }
		}
		catch(SQLException e) 
		{
			e.printStackTrace();
		}
		
		return trobat;

	}

	/**
	 * 
	 * @param matricula 
	 * @param Existeix 
	 */
	public static void comprovarMatricula(String matricula, boolean Existeix) {
	}

	/**
	 * 
	 * @param DNI 
	 * @param Client 
	 */
	public static void consultaClient(String DNI, Cliente Client) {
	}

	/**
	 * 
	 * @param Matricula 
	 * @param Vehiculo 
	 */
	public static void consultaVehiculo(String Matricula, Vehiculo Vehiculo) {
	}

	/**
	 * 
	 * @param codigoArticulo 
	 * @param Articulo 
	 */
	public static Articulos consultaArticulo(String codigoArticulo, Database db) {
		
		
		String codigo = "";
		String nombre = "";
		float precio = 0;
		float iva = 0;
		
		
		try 
		{
            ResultSet rs = db.ExecuteQuery("SELECT * FROM articulos WHERE codigo = '"+codigoArticulo+"';");
            while (rs.next()) 
            {
            	codigo = rs.getString(1);
            	nombre = rs.getString(2);
            	precio = rs.getFloat(3);
            	iva = rs.getFloat(4);
            }
		}
		catch(SQLException e) 
		{
			e.printStackTrace();
		}
		
		Articulos articulo = new Articulos(codigo,nombre,precio,iva);
		
		return articulo;
	}

	/**
	 * 
	 * @param numFactura 
	 * @param Factura 
	 */
	public static void consultaFactura(int numFactura, FacturaHeader Factura) {
	}

	/**
	 * 
	 * @param numFactura 
	 * @param Existeix 
	 */
	public static void comprovarNumeroFactura(String numFactura, boolean Existeix) {
	}
};
