// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package motauto;

/************************************************************/
/**
 * 
 */
public class FacturaFiles {

	private int cantidad;
	private Articulos articulos;
	private FacturaHeader facturasHeader;
	private float descuento;
	private float precio_total;
	
	FacturaFiles(int cantidad, Articulos articulo,FacturaHeader facturaHeader, float descuento, float precio_total)
	{
		this.cantidad = cantidad;
		this.articulos = articulo;
		this.facturasHeader = facturaHeader;
		this.descuento = descuento;
	}

	public int getCantidad() {
		return cantidad;
	}
	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}
	public Articulos getArticulos() {
		return articulos;
	}
	public void setArticulos(Articulos articulos) {
		this.articulos = articulos;
	}
	public FacturaHeader getFacturasHeader() {
		return facturasHeader;
	}
	public void setFacturasHeader(FacturaHeader facturasHeader) {
		this.facturasHeader = facturasHeader;
	}
	public float getDescuento() {
		return descuento;
	}
	public void setDescuento(int descuento) {
		this.descuento = descuento;
	}

	public float getPrecio_total() {
		return precio_total;
	}

	public void setPrecio_total(float precio_total) {
		this.precio_total = precio_total;
	}
	
	public boolean insertFacturaFila(Database db) {
		boolean creacionCorrecta = false;

		try 
		{
		creacionCorrecta = db.ExecuteUpdate("INSERT INTO facturas_filas (codigo_articulo,nombre,cantidad,descuento,precio_total) VALUES ("+ this.articulos.getCodigo() +","+ this.articulos.getNombre() + ","+ this.cantidad +","+ this.descuento + "," + this.precio_total  + ");");			
		System.out.println(creacionCorrecta ? "Insert Correcte" : "Insert Incorrecte");
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
		
		return creacionCorrecta;
	}
}
