// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package motauto;

/************************************************************/
/**
 * 
 */
 class FacturaHeader {
				/**
				 * 
				 */
				public int numPressupost;
				/**
				 * 
				 */
				public String cifEmpresa;
				/**
				 * 
				 */
				public int estado;
				/**
				 * 
				 */
				public EcorePrimitiveTypes.EFloat total;
				/**
				 * 
				 */
				public Cliente Cliente;
				/**
				 * 
				 */
				public Vehiculo Vehiculo;
				/**
				 * 
				 */
				public Articulos Articulos;
				/**
				 * 
				 */
				public FacturaFiles ArrayFacturaFiles;
				/**
				 * 
				 */
				public undefined Descuento Factura;
				/**
				 * 
				 */
				public undefined Total Iva;
				/**
				 * 
				 */
				public undefined Total Factura;
				/**
				 * 
				 */
				public undefined Observaciones;
				/**
				 * 
				 */
				public EcorePrimitiveTypes.EDate Data Factura;
	/**
	 * 
	 * @param InsertFacturaCompletat 
	 */
	public void insertFactura(undefined InsertFacturaCompletat) {
	}
	/**
	 * 
	 * @param UpdateFacturaCompletat 
	 */
	public void modificarFactura(undefined UpdateFacturaCompletat) {
	}
	/**
	 * 
	 */
	public void imprimirFactura() {
	}
};
