// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package motauto;

import java.time.LocalDate;

/************************************************************/
/**
 * 
 */
 class FacturaHeader {
				/**
				 * 
				 */
				public int numPressupost;
				/**
				 * 
				 */
				public String cifEmpresa;
				/**
				 * 
				 */
				public int estado;
				/**
				 * 
				 */
				public float total;
				/**
				 * 
				 */
				public Cliente Cliente;
				/**
				 * 
				 */
				public Vehiculo Vehiculo;
				/**
				 * 
				 */
				public Articulos Articulos;
				/**
				 * 
				 */
				public FacturaFiles ArrayFacturaFiles;
				/**
				 * 
				 */
				public int DescuentoFactura;
				/**
				 * 
				 */
				public float TotalIva;
				/**
				 * 
				 */
				public float TotalFactura;
				/**
				 * 
				 */
				public String Observaciones;
				/**
				 * 
				 */
				public LocalDate DataFactura;
	/**
	 * 
	 * @param InsertFacturaCompletat 
	 */
	public void insertFactura(boolean InsertFacturaCompletat) {
	}
	/**
	 * 
	 * @param UpdateFacturaCompletat 
	 */
	public void modificarFactura(boolean UpdateFacturaCompletat) {
	}
	/**
	 * 
	 */
	public void imprimirFactura() {
	}
};
