// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package motauto;

/************************************************************/
/**
 * 
 */
public class FacturaFiles {
	/**
	 * 
	 */
	public int cantidad;
	/**
	 * 
	 */
	public Articulos Articulos;
	/**
	 * 
	 */
	public FacturaHeader FacturasHeader;
	/**
	 * 
	 */
	public int Descuento;
};
