// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package motauto;

/************************************************************/
/**
 * 
 */
public class Modificacions {
	/**
	 * 
	 * @param ObjecteClient 
	 */
	public static void altaCliente(undefined ObjecteClient) {
	}

	/**
	 * 
	 * @param ObjectArticulo 
	 */
	public static void altaArticulo(undefined ObjectArticulo) {
	}

	/**
	 * 
	 * @param ObjecteVehicle 
	 */
	public static void altaVehiculo(undefined ObjecteVehicle) {
	}

	/**
	 * 
	 * @param dni 
	 */
	public static void borrarCliente(String dni) {
	}

	/**
	 * 
	 * @param codigoArticulo 
	 */
	public static void borrarArticulo(String codigoArticulo) {
	}

	/**
	 * 
	 * @param matricula 
	 */
	public static void borrarVehiculo(String matricula) {
	}

	/**
	 * 
	 * @param cantidadArticulo 
	 * @param precioArticulo 
	 * @param iva 
	 * @param Descuento 
	 */
	public static void calcularTotal(int cantidadArticulo, EcorePrimitiveTypes.EFloat precioArticulo,
			EcorePrimitiveTypes.EFloat iva, int Descuento) {
	}

	/**
	 * 
	 * @param FacturaHeader 
	 * @param FacturaFiles 
	 */
	public static void altaFactura(FacturaHeader FacturaHeader, FacturaFiles FacturaFiles) {
	}

	/**
	 * 
	 * @param esborrat 
	 * @param numFactura 
	 */
	public static void borrarFactura(boolean esborrat, String numFactura) {
	}

	/**
	 * 
	 * @param ObjecteVehicle 
	 */
	public static void ModificarVehiculo(undefined ObjecteVehicle) {
	}

	/**
	 * 
	 * @param FacturaHeader 
	 * @param FacturaFiles 
	 */
	public static void Modificar

	Factura(FacturaHeader FacturaHeader, FacturaFiles FacturaFiles) {
	}

	/**
	 * 
	 * @param ObjecteClient 
	 */
	public static void ModificarCliente(undefined ObjecteClient) {
	}

	/**
	 * 
	 * @param ObjectArticulo 
	 */
	public static void ModificarAriculo(undefined ObjectArticulo) {
	}
};
