// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package motauto;

/************************************************************/
/**
 * 
 */
public class Utiles {
	/**
	 * 
	 * @param numero 
	 */
	public static void demanarInteger(int numero) {
	}

	/**
	 * 
	 * @param dni 
	 */
	public static void demanarDni(String dni) {
	}
};
