// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package motauto;

/************************************************************/
/**
 * 
 */
public class Vehiculo {
	/**
	 * 
	 */
	private static String matricula;
	/**
	 * 
	 */
	public Cliente Cliente;

	/**
	 * 
	 * @param Insert Correcte 
	 */
	public static void insertVehiculo(boolean Insert Correcte) {
	}

	/**
	 * 
	 */
	public static void modificarVehiculo() {
	}

	/**
	 * 
	 */
	public void imprimirVehicle() {
	}
};
